# Generated by Django 5.2.4 on 2025-07-10 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'core_post', 'verbose_name_plural': 'core_posts'},
        ),
    ]
